# Generated by Django 4.0.4 on 2022-05-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='https://robohash.org/{id}', upload_to='avatars'),
        ),
    ]
